### ISSUE TITLE
Возможность переопределить алгоритм обработки хешей для useParams

### ISSUE THREAD

**Issue by MWGuy** [land47/router#13]
Конечно, запись вида ``vk.com/app123#panel=about&hash=000&id=123`` хороша, но хотелось бы иметь функционал что-бы получить те-же самые данные, но по другому формату хеша.

К примеру определить singleton функцию типа ``(hash: string): SerializedURLParams`` для обработки своих форматов хешей.

Пример из реальной жизни:
* https://vk.com/manga_app#solo-leveling
* https://vk.com/manga_app#team/starfallgroup

**Comment by evtn** [comment]
обработки*

**Comment by land47** [comment]
На текущий момент роутер не умеет обрабатывать хеш (скоро реализую), но есть пример, показывающий в какую сторону двигаться
https://gist.github.com/land47/e81c8aaf465f9b8201c146880201ff36
