### ISSUE TITLE
ClosePopout в ActionSheet дублирует вызов события

### ISSUE THREAD

**Issue by ub1x** [land47/router#16]
<ActionSheet onClose={closePopout} ... /> 
при закрытии ДВАЖДЫ вызывает событие onClose, что приводит к возврату на прошлую страницу.

**Comment by ub1x** [comment]
Антон Захарьев @land47 самый уважаемый человек в своей квартире, я очень надеюсь на то, что Вы исправите это поскорее!!!!

**Comment by land47** [comment]
https://github.com/VKCOM/VKUI/issues/1385
