### ISSUE TITLE
Остановка роутинга

### ISSUE THREAD

**Issue by ub1x** [land47/router#22]
Мой кейс:
Игнорировать любые вызовы back и т.д. в случае, если человек находится на конкретной панели.
Предполагаю что можно сделать хук, условно useNavigation(Boolean), и если передать false - любые события ДО установки true будут игнорироваться

**Comment by land47** [comment]
Потенциально, такая возможность [есть](https://github.com/land47/router/blob/52f54db84e1463b8f8fc645e0fa62e7f51002983/router/base/Navigator.ts#L279), но в текущей версии доступ до этого метода не получить. Стоит ожидать в новой версии

**Comment by land47** [comment]
Сейчас, помощью хука ```useNavigator```, можно получить доступ до метода ```freezeLifecycle```
