### ISSUE TITLE
replace криво заменяет popout

### ISSUE THREAD

**Issue by ub1x** [land47/router#23]
В попытке сделать replace({popout: <anyJSX />}) мы ловим на экране [Object object], а это очень нужный момент особенно со скрин-спиннером, к которому через setPopout можно вернуться (чего не должно быть по логике, ведь это UI загрузки)

**Comment by land47** [comment]
Для управления всплывающими окнами, следует использовать хук `usePopout`. Ознакомится с документацией можно [здесь](https://github.com/land47/router).
