### ISSUE TITLE
Множественный вызов useSwipeBack ломает роутинг 

### ISSUE THREAD

**Issue by VMatyagin** [land47/router#31]
Если вызвать этот хук не один раз в корне приложения, а рядом с каждым View, то роутинг виснет намертво, оживает через довольно продолжительное время. В примере он вызывается в AbstractView. Если закомменить, то все ок

[Ссылка на Sandbox](https://codesandbox.io/s/nice-euclid-nd7fi?file=/src/AbstractView.jsx)

**Comment by land47** [comment]
Хук useSwipeback более не поддерживается. В релизе @unexp/router@beta обработкой свайпов занимается компонент [Match](https://github.com/land47/router/blob/main/docs/api.md#match)
