### ISSUE TITLE
Перестает работать при большой вложенности

### ISSUE THREAD

**Issue by VMatyagin** [land47/router#32]
## CODESANDBOX
https://codesandbox.io/s/festive-stallman-9vuhx?file=/src/_app.js

## Expected Behavior
Панель "/" должна смениться на "/list"

## Current Behavior
Панель не сменятся

Респект за либу с такими возможностями. Правда помимо вышеуказанной проблемы у меня возникли следующие:

1. Если в одном компоненте с `<Match /> `лежит что-то из react-query, то просто ничего не отрендерит.
2. Видимо нужно, чтобы  `<Panel />` был прямым чилдом `<View />` и так до самого `<Epic/>`. Например, у меня есть AbstractView с инкапсулированной логикой, в нем лежит `<View nav={nav} />` и он просто ничего не отрендерит.
3. Иногда, скажем, при `<Link t={-1} />` location меняется, а отрендерна старая панель

Могу создать для каждой отдельной проблемы issue с примером

**Comment by land47** [comment]
Привет! Хорошие замечания.
1.  Изучу данное поведение (для отслеживания прогресса можно завести отдельным ишью)
2. Да, верно, нужно определять структуру приложения внутри компонента **Match**
3. Давай разберемся с этим в рамках нового ишью (желательно с примером)

Основную проблему исправил в **@1.0.0-beta2**

**Comment by land47** [comment]
Важное замечание: начиная с этой версии импортировать **Epic** / **Root** / **View** нужно будет из индексного файла роутера.

```js
import {Epic, Root, View} from '@unexp/router'
```

Этот хак применяется для исправления проблем с TypeScript
