### ISSUE TITLE
Не работают popoutы

### ISSUE THREAD

**Issue by VadimTVJ** [land47/router#35]
Привет! Отвалились попауты :(

https://codesandbox.io/s/popouts-ysz2m

**Comment by VadimTVJ** [comment]
И еще ты говорил для попаутов надо использовать хук (https://github.com/land47/router/issues/23#issuecomment-774383647)
Но нигде не нашел ни упоминаний в доке, ни в самом коде :(

**Comment by VadimTVJ** [comment]
И еще вопросик, не буду отдельное ишью создавать
Планируется ли поддержка ViewInfinite?

**Comment by land47** [comment]
> И еще ты говорил для попаутов надо использовать хук

Так было в прошлой версии, сейчас роутер переписывается: над ним ведется большая работа по улучшению UX и DX

> Планируется ли поддержка ViewInfinite?

Планируется, примерных сроков не назвать

**Comment by land47** [comment]
Исправлено в **@v1.0.0-beta6**
